env:
  - TARGET=NAZE
  - TARGET=NAZE32PRO

# use new docker environment
sudo: false

addons:
  apt:
    packages:
      - build-essential
      - git
      - libc6-i386
      - zlib1g-dev
      - libssl-dev
      - wkhtmltopdf
      - libxml2-dev
      - libxslt-dev

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: clang

before_install:
  - curl --retry 10 --retry-max-time 120 -L "https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2" | tar xfj -

install:
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-4_9-2015q2/bin

before_script: arm-none-eabi-gcc --version
script: ./.travis.sh

cache: apt

notifications:
  irc: "chat.freenode.net#cleanflight"
  use_notice: true
  skip_join: true